apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ template "fullname" . }}
  type: {{ default "ClusterIP" .Values.serviceType | quote }}
