# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: acrjdtest.azurecr.io/jldeen/sentry-demo
  tag: master
  pullPolicy: Always
## If you have a private registry you specify a secret to use
imagePullSecrets: 
  name: sentrydemo
  email: ServicePrincipal@AzureRM
serviceName: sentrydemo
serviceType: ClusterIP
servicePort: 80
containerPort: 8080
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: true
  hostname: sentrydemo.k8s.az.jessicadeen.com
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  tls: true